/*
 * JQueryScrollTopDemo
 * © 2013 Force.com Developer
 * ----------------------------------------
 * @createdDate      : 2013/01/01
 * @createdName      : TAIKI,YOSHIKAWA
 * ----------------------------------------
 * @lastModifiedDate : 2013/01/01
 * @lastModifiedName : TAIKI,YOSHIKAWA
 * ----------------------------------------
 */
public with sharing class PageScrollTopButtonDemoController {
	
	/*
	 * コンストラクタ
	 * @param	: なし
	 * @return	: なし
	 */
	public PageScrollTopButtonDemoController() {
		
	}
}