/**
 * JQueryScrollTopDemo
 * © 2013 Force.com Developer
 * ----------------------------------------
 * @createdName      : Taiki,Yoshikawa
 * @lastModifiedName : Taiki,Yoshikawa
 * ----------------------------------------
 */
@isTest
private class PageScrollTopButtonDemoControllerTest {

    /**
     * コンストラクタ
     */
    static testMethod void PageScrollTopButtonDemoControllerTest() {
            
        Test.startTest();
        
        // コンストラクタ
        PageScrollTopButtonDemoController cls = new PageScrollTopButtonDemoController();
        
        Test.stopTest();
    }
}